#!/bin/bash
#BSUB -J myjobMPI
#BSUB -n 6
#BSUB -R span[ptile=6]
#BSUB -R rusage[mem=64]
#BSUB -W 20:00
#BSUB -o %J.stdout
#BSUB -eo %J.stderr
# Bamcompare to generate comparison file bw different treatment
bamCompare -b1  K562_PH_Half_E_1.bam  -b2 K562_PH_Half_1.bam  -o K562_PH_HALF_CK&Enzy.bw
