#!/bin/bash
# To creat matrix of bigwig to whole genome
#BSUB -J myjobMPI
#BSUB -n 16
#BSUB -R span[ptile=16]
#BSUB -R rusage[mem=4]
#BSUB -W 20:00
#BSUB -o %J.stdout
#BSUB -eo %J.stderr

computeMatrix scale-regions -S *_S15_*.bw -R ./hg38_bed/Homo_sapiens.GRCh38.93.gene.bed -a 3000 -b 3000 -m 10000 -o test.matrix.gz -p 16
