#!/bin/bash
#BSUB -J myjobMPI
#BSUB -n 6
#BSUB -R span[ptile=6]
#BSUB -R rusage[mem=64]
#BSUB -W 20:00
#BSUB -o %J.stdout
#BSUB -eo %J.stderr
plotHeatmap -m R_loop_sample.matrix.gz -out R_loop_sample.matrix.gz.pdf --dpi 1200 --colorMap Blues --missingDataColor white
